apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodepod-service
spec:
  type: NodePort
  selector:
    app: prometheus-server
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 32500
