Vagrant.configure("2") do |config|
    config.vm.box = "chenhan/ubuntu-desktop-20.04"
    config.vm.box_version = "20200424"
    config.vm.hostname = "worker-01"
    config.vm.box_download_insecure = true
    config.vm.provider "virtualbox" do |v|
        v.gui = true
        v.linked_clone = false
    end
    config.vm.provision "shell", path: "./install.sh"
  
  end